### ISSUE TITLE
[function.session-start]

### ISSUE THREAD

**Issue by Foamable** [sinanisler/snn-brx-child-theme#2]
Hello Dear Sinanisler

Before noob-diving into your "function.session.start" file and mock around,
I wanted to ask if have you encouted this message before?

Warning:
session_start() [[function.session-start](http://php.net/manual/en/function.session-start)]:
Cannot start session when headers already sent in /var/www/omdollar.com/...my subfolder... /wp-content/themes/snn-brx-child-theme/includes/login-math-captcha.php on line 6.

At any rate, things is working perfectly, besides the message.

![SNN-BRX_ChildTheme_warning](https://github.com/user-attachments/assets/7d2c8b4e-d88e-4179-b611-5ddfff0e4fa7)

Huge Thanks - Awesome Child theme tweaks
//Jacob

**Comment by sinanisler** [comment]
interesting 
ok will check that later

**Comment by sinanisler** [comment]
install the latest release made a fix 
it should be fine now

**Comment by Foamable** [comment]
Correct - Solved:}
