### ISSUE TITLE
Adding License

### ISSUE THREAD

**Issue by JasperDaDolphin** [sinanisler/snn-brx-child-theme#6]
Hello,

I noticed that this repository currently does not have a license file. Without a license, it's unclear how others can use, modify, or distribute the code. Adding an appropriate open-source license would help clarify the terms under which the code can be used and would encourage contributions from the community.

Would it be possible to add a license file to this repository? If you're unsure which license to choose, you might consider popular options like MIT, Apache 2.0, or GPL. GitHub also provides a [guide](https://choosealicense.com/) to help with selecting a license.

Thank you!

**Comment by sinanisler** [comment]
sure added
